# Generated by Django 2.0.4 on 2018-05-14 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField(max_length=100, verbose_name='Descuento')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha fin')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
