# Generated by Django 2.0.4 on 2018-05-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='descuento',
            field=models.IntegerField(verbose_name='Descuento'),
        ),
    ]
