# Generated by Django 2.0.4 on 2018-05-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180514_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['id'], 'verbose_name': 'oferta', 'verbose_name_plural': 'ofertas'},
        ),
    ]
