# Generated by Django 2.0.4 on 2018-05-14 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20180514_1656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_buy_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ['title'], 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AddField(
            model_name='buy',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sales', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='listacursos',
            name='cursos',
            field=models.ManyToManyField(related_name='anadirCarrito', to='course.Buy', verbose_name='Cursos'),
        ),
    ]
