# Generated by Django 2.0.4 on 2018-05-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180514_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listacursos',
            options={'ordering': ['cliente'], 'verbose_name': 'lista_curso', 'verbose_name_plural': 'lista_cursos'},
        ),
        migrations.RenameField(
            model_name='listacursos',
            old_name='author',
            new_name='cliente',
        ),
    ]
